version: '3'

services:
  drop-db:
    image: mongo:4.1.8-xenial
    container_name: drop-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - ./db/data:/data/db
    networks:
      - app-network
    ports:
      - 27017:27017

  drop-api:
    image: theniceninja13/drop-api
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOST=drop-db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "8000:3000"
      - "8443:3443"
    networks:
      - app-network
    depends_on:
      - drop-db
    links:
      - drop-db

networks:
  app-network:
    driver: bridge

volumes:
  data:
